### ISSUE TITLE
Sobre o inspect 

### ISSUE THREAD

**Issue by flschiavoni** [jahpd/termpot#2]
O inspect poderia ter exemplos de como usar a função.
Atualmente ele retorna apenas a implementação da função.

**Comment by jahpd** [comment]
Acho que para isso deve-se criar uma API, tlvz na função register_fn e criar um outro escopo para páginas de ajuda?

**Comment by jahpd** [comment]
No branch coffeescript foi solucionado esse problema

É possível agora registrar módulos em uma linha junto com sua documentação:

```
def modulo(a, b, c) a+b+c  #  Retorna documentacao sobre a soma
```

O primeiro token `def` define o a função `modulo` com argumentos `a, b, c`. Depois `a+b+c` define o escopo da função. O que estiver após `#` será utilizado como documentação rápida.

Para verificar a documentação, utilizar `inspect modulo`

Acho que dá pra fechar essa issue, mas espero tua resposta
